allFiles: bin2dec.c bin2hex.c dec2bin.c hex2bin.c
        gcc -Wall bin2dec.c -o bin2dec.out -lm
        gcc -Wall bin2hex.c -o bin2hex.out -lm
        gcc -Wall dec2bin.c -o dec2bin.out -lm
        gcc -Wall hex2bin.c -o hex2bin.out -lm
clean:
     rm *.o bin2dec.out bin2hex.out dec2bin.out hex2bin.out
